import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import type { AtxDoc } from '../services/api';

/**
 * ATX Documentation tab.
 *
 * The reported defect: after an analysis completed, the tab showed nothing. Three
 * behaviours are pinned here:
 *
 * - collected markdown is rendered AS markdown (headings become headings), not as
 *   raw text and never as a metadata JSON dump;
 * - each empty state names its actual cause — still running, produced nothing,
 *   or failed to load are three different messages;
 * - selecting a document loads that document.
 */

const getAtxConversationDocs = vi.fn();
const getAtxFileContent = vi.fn();

vi.mock('../services/api', () => ({
  getAtxConversationDocs: (...args: unknown[]) => getAtxConversationDocs(...args),
  getAtxFileContent: (...args: unknown[]) => getAtxFileContent(...args),
}));

const { AtxDocumentationPanel } = await import('./AtxDocumentationPanel');

const CONVERSATION_ID = 'atx_20250101_120000_abcd1234';

const scrollIntoView = vi.fn();
Element.prototype.scrollIntoView = scrollIntoView;

const DOCS: AtxDoc[] = [
  {
    name: 'README.md',
    path: 'README.md',
    storage_path: `${CONVERSATION_ID}/docs/README.md`,
    size: 42,
  },
  {
    name: 'system-overview.md',
    path: 'architecture/system-overview.md',
    storage_path: `${CONVERSATION_ID}/docs/architecture/system-overview.md`,
    size: 128,
  },
];

/**
 * A document set shaped like real `AWS/comprehensive-codebase-analysis` output: an index at
 * the root and siblings inside subdirectories. `architecture/components.md` is first so it
 * is the auto-selected document, which is what makes `../` traversal observable.
 */
const NESTED_DOCS: AtxDoc[] = [
  {
    name: 'components.md',
    path: 'architecture/components.md',
    storage_path: `${CONVERSATION_ID}/docs/architecture/components.md`,
    size: 200,
  },
  {
    name: 'system-overview.md',
    path: 'architecture/system-overview.md',
    storage_path: `${CONVERSATION_ID}/docs/architecture/system-overview.md`,
    size: 128,
  },
  {
    name: 'api-reference.md',
    path: 'reference/api-reference.md',
    storage_path: `${CONVERSATION_ID}/docs/reference/api-reference.md`,
    size: 300,
  },
];

beforeEach(() => {
  getAtxConversationDocs.mockReset();
  getAtxFileContent.mockReset();
  scrollIntoView.mockReset();
});

describe('AtxDocumentationPanel', () => {
  it('renders collected markdown as markdown, not raw text or metadata', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: DOCS, status: 'completed' });
    getAtxFileContent.mockResolvedValue('# ATX Documentation\n\nGenerated by the analysis.\n');

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);

    // Heading text arrives as an actual heading element — proof of markdown rendering.
    const heading = await screen.findByRole('heading', { name: 'ATX Documentation' });
    expect(heading).toBeInTheDocument();
    expect(screen.getByText('Generated by the analysis.')).toBeInTheDocument();

    // The literal markdown source must not be shown, and neither must metadata.
    expect(screen.queryByText(/# ATX Documentation/)).not.toBeInTheDocument();
    expect(screen.queryByText(/storage_path/)).not.toBeInTheDocument();

    // Content is fetched through the agent's /file reader for the first document.
    expect(getAtxFileContent).toHaveBeenCalledWith(DOCS[0].storage_path);
  });

  it('loads the document the user selects', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('system-overview.md') ? '# System Overview\n' : '# ATX Documentation\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'ATX Documentation' });

    fireEvent.click(screen.getByText('system-overview.md'));

    expect(await screen.findByRole('heading', { name: 'System Overview' })).toBeInTheDocument();
    expect(getAtxFileContent).toHaveBeenCalledWith(DOCS[1].storage_path);
  });

  it('says the analysis produced nothing when a completed run has no documents', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: [], status: 'completed' });

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);

    expect(
      await screen.findByText(/completed without producing any documentation artifacts/i)
    ).toBeInTheDocument();
  });

  it('distinguishes a still-running analysis from one that produced nothing', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: [], status: 'running' });

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);

    expect(await screen.findByText(/still running/i)).toBeInTheDocument();
    expect(screen.queryByText(/without producing any documentation/i)).not.toBeInTheDocument();
  });

  it('distinguishes a load failure from an absence of documents', async () => {
    getAtxConversationDocs.mockRejectedValue(new Error('Network Error'));

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);

    expect(await screen.findByText(/Could not load documentation/i)).toBeInTheDocument();
    expect(screen.getByText(/Network Error/)).toBeInTheDocument();
    expect(screen.queryByText(/without producing any documentation/i)).not.toBeInTheDocument();
  });

  it('follows a relative cross-document link by selecting that document in the panel', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('system-overview.md')
        ? '# System Overview\n'
        : '# Index\n\n[System Overview](architecture/system-overview.md)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Index' });

    fireEvent.click(screen.getByText('System Overview'));

    expect(await screen.findByRole('heading', { name: 'System Overview' })).toBeInTheDocument();
    expect(getAtxFileContent).toHaveBeenCalledWith(DOCS[1].storage_path);
  });

  it('asks for a conversation when none is selected', async () => {
    render(<AtxDocumentationPanel conversationId={null} />);

    expect(screen.getByText(/Select a conversation to view its documentation/i)).toBeInTheDocument();
    await waitFor(() => expect(getAtxConversationDocs).not.toHaveBeenCalled());
  });
});

/**
 * Cross-document links.
 *
 * The reported defect: every link in the generated documentation was dead. The ATX index
 * links its 32 siblings by relative path, and each one rendered as `target="_blank"` to a
 * URL like `/architecture/system-overview.md` that the SPA cannot serve. The documents were
 * already loaded and addressable — the links just were not wired to them.
 */
describe('AtxDocumentationPanel cross-document links', () => {
  it('resolves a relative link against the open document\'s own directory', async () => {
    // `system-overview.md` inside `architecture/components.md` means
    // `architecture/system-overview.md`, not a top-level file. Resolving against the
    // collection root instead would find nothing.
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('architecture/system-overview.md')
        ? '# System Overview\n'
        : '# Components\n\n[System Overview](system-overview.md)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    fireEvent.click(screen.getByText('System Overview'));

    expect(await screen.findByRole('heading', { name: 'System Overview' })).toBeInTheDocument();
    expect(getAtxFileContent).toHaveBeenCalledWith(NESTED_DOCS[1].storage_path);
  });

  it('resolves ../ traversal out of one subdirectory into another', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('reference/api-reference.md')
        ? '# API Reference\n'
        : '# Components\n\n[API Reference](../reference/api-reference.md)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    fireEvent.click(screen.getByText('API Reference'));

    expect(await screen.findByRole('heading', { name: 'API Reference' })).toBeInTheDocument();
    expect(getAtxFileContent).toHaveBeenCalledWith(NESTED_DOCS[2].storage_path);
  });

  it('selects the document and scrolls to the anchor for a cross-document fragment', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('reference/api-reference.md')
        ? '# API Reference\n\n## Authentication\n\nBearer tokens.\n'
        : '# Components\n\n[Auth](../reference/api-reference.md#authentication)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    fireEvent.click(screen.getByText('Auth'));

    // The document is selected...
    const target = await screen.findByRole('heading', { name: 'Authentication' });
    // ...and the anchor is scrolled to only once its markup exists, not in the click tick.
    await waitFor(() => expect(scrollIntoView).toHaveBeenCalled());
    expect(scrollIntoView.mock.instances[0]).toBe(target);
  });

  it('keeps the side list selection in step with an in-panel navigation', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('architecture/system-overview.md')
        ? '# System Overview\n'
        : '# Components\n\n[System Overview](system-overview.md)\n'
    );

    const { container } = render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    const entryFor = (name: string) =>
      screen.getByText(name).closest('.MuiListItemButton-root') as HTMLElement;

    expect(entryFor('components.md').className).toContain('Mui-selected');

    fireEvent.click(container.querySelector('[data-doc-path]') as HTMLElement);
    await screen.findByRole('heading', { name: 'System Overview' });

    expect(entryFor('system-overview.md').className).toContain('Mui-selected');
    expect(entryFor('components.md').className).not.toContain('Mui-selected');
  });

  it('offers a way back after following a link into a subdocument', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockImplementation(async (path: string) =>
      path.endsWith('architecture/system-overview.md')
        ? '# System Overview\n'
        : '# Components\n\n[System Overview](system-overview.md)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });
    expect(screen.queryByRole('button', { name: /^Back to/ })).not.toBeInTheDocument();

    fireEvent.click(screen.getByText('System Overview'));
    await screen.findByRole('heading', { name: 'System Overview' });

    const back = screen.getByRole('button', { name: /Back to components\.md/ });
    fireEvent.click(back);

    expect(await screen.findByRole('heading', { name: 'Components' })).toBeInTheDocument();
  });

  it('does not render an unresolvable relative link as a navigable link', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockResolvedValue('# Components\n\n[Missing Doc](nowhere/absent.md)\n');

    const { container } = render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    // No anchor at all — neither a dead new tab nor a click that silently does nothing.
    expect(container.querySelector('a[href*="absent.md"]')).toBeNull();
    expect(container.querySelector('a[target="_blank"]')).toBeNull();

    const unresolved = container.querySelector('[data-unresolved-link]') as HTMLElement;
    expect(unresolved).not.toBeNull();
    expect(unresolved.tagName).toBe('SPAN');
    expect(unresolved).toHaveAttribute('aria-disabled', 'true');
    // The explanation names the target that could not be found.
    expect(unresolved.getAttribute('title')).toContain('nowhere/absent.md');
    expect(unresolved).toHaveTextContent('Missing Doc');
  });

  it('keeps external links opening in a new tab', async () => {
    getAtxConversationDocs.mockResolvedValue({ docs: NESTED_DOCS, status: 'completed' });
    getAtxFileContent.mockResolvedValue(
      '# Components\n\n[AWS](https://aws.amazon.com/) and [mail](mailto:team@example.com)\n'
    );

    render(<AtxDocumentationPanel conversationId={CONVERSATION_ID} />);
    await screen.findByRole('heading', { name: 'Components' });

    const external = screen.getByRole('link', { name: 'AWS' });
    expect(external).toHaveAttribute('href', 'https://aws.amazon.com/');
    expect(external).toHaveAttribute('target', '_blank');
    expect(external).toHaveAttribute('rel', 'noopener noreferrer');

    expect(screen.getByRole('link', { name: 'mail' })).toHaveAttribute('target', '_blank');
  });
});
